version: '3.3'

networks:
  back:
    # use a custom driver, with no options
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.239.0/24

services:
  selenium-hub:
    image: selenium/hub:3.141.59-dubnium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      back:
        ipv4_address: 172.16.239.8
    logging:
      driver: json-file

  firefox:
    image: selenium/node-firefox:3.141.59-dubnium
    container_name: selenium-hub-firefox
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      back:
        ipv4_address: 172.16.239.9
    logging:
      driver: json-file
    entrypoint: bash -c 'SE_OPTS="-timeout 60" /opt/bin/entry_point.sh'
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "curl --silent http://172.16.239.8:4444/wd/hub/status | grep ready | grep true"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
       back:
        ipv4_address: 172.16.239.11
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "mongo --eval 'db.version()'"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  lmtp-server:
    depends_on:
      - mongodb
    build:
      context: ./lmtp-server
    ports:
     - "10025:10025"
    networks:
       back:
        ipv4_address: 172.16.239.12
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/usr/bin/curl --silent -f smtp://172.16.239.12:10025 --mail-from myself@example.com --mail-rcpt myself@example.com > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  tester:
    depends_on:
      - lmtp-server
      - trashmail-client
      - firefox
    build:
      context: ./tester
    volumes:
      - /dev/shm:/dev/shm
    networks:
      back:
        ipv4_address: 172.16.239.10
    logging:
      driver: json-file

  trashmail-client:
    depends_on:
      - mongodb
    build:
      context: ./trashmail-client
    ports:
      - "3000:3000"
    networks:
      back:
        ipv4_address: 172.16.239.13
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/usr/bin/curl --silent -f http://172.16.239.13:3000 > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

