#!/usr/bin/env bash

service="$1"
DO_SHUTDOWN=1

which curl || exit 1

for i in lmtp-server trashmail-client; do
  docker-compose build --no-cache "$i"
done

if [ -z "$service" ]; then
  docker-compose up -d --no-deps --force-recreate $service || exit 1
else
  docker-compose up -d --scale tester=0 || exit 1
fi

count=30
while : ; do
  docker-compose ps lmtp-server | grep healthy
  if [ $? -eq 0 ]; then break; fi
  sleep 1
  let count=${count}-1
  if [ $count -eq 0 ]; then exit 1; fi
done
echo "lmtp-server ready for service"

count=30
while : ; do
  docker-compose ps firefox | grep healthy
  if [ $? -eq 0 ]; then break; fi
  sleep 1
  let count=${count}-1
  if [ $count -eq 0 ]; then exit 1; fi
done
echo "selenium firefox ready for service"

count=30
while : ; do
  docker-compose ps trashmail-client | grep healthy
  if [ $? -eq 0 ]; then break; fi
  sleep 1
  let count=${count}-1
  if [ $count -eq 0 ]; then exit 1; fi
done
echo "trashmail-client (test subject) ready for service"

ECHO=echo
docker-compose up tester
if [ $? -eq 0 ]; then
  $ECHO "success"
  res=0
else
  $ECHO "failed"
  res=1
fi

if [ $DO_SHUTDOWN -eq 1 ]; then
  docker-compose down
fi

exit $res

