#!/usr/bin/env bash

service="$1"
DO_SHUTDOWN=1

which curl || exit 1

for i in lmtp-server trashmail-client; do
  docker-compose build --no-cache "$i"
done

if [ -z "$service" ]; then
  docker-compose up -d --no-deps --force-recreate $service || exit 1
else
  docker-compose up -d --scale tester=0 || exit 1
fi

while : ; do
  docker-compose ps lmtp-server | grep healthy
  if [ $? -eq 0 ]; then break; fi
done

while : ; do
  docker-compose ps firefox | grep healthy
  if [ $? -eq 0 ]; then break; fi
done

docker-compose up tester
if [ $? -eq 0 ]; then
  echo "success"
  res=0
else
  echo "failed"
  res=1
fi

if [ $DO_SHUTDOWN -eq 1 ]; then
  docker-compose down
fi

exit $res

